# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Grizzlybit"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Grizzlybit is a JavaScript programmer's blog about his thoughts, ideas and stories"
 
# Tagline near the site title
tagline: "A coder's digest that is trying to be quirky, flawed and an enormous success."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://grizzlybit.info"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
#- text: Style Guides
#  url: /style-guide/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: grizzlybit-1

# Author information - author info at the bottom of the post
author_name: "Zubair Ahmed"
author_bio: "Zubair Ahmed is ambitious tweaker who seeks adventures. He likes slapping the keyboard until something good happens."
author_url:  "http://grizzlybit.info/about/"
author_location: "Dubai, United Arab Emirates"
author_image: /images/Zubair_Ahmed.jpg

# Sidebar Add banner
banner_url: "http://grizzlybit.info"
banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//Grizzlybit.us13.list-manage.com/subscribe/post?u=f62123446eb4d2d91c25180f8&amp;id=aceae531dd"

# Social links in the site footer
twitter_username: "zubair1024"
facebook_username: "zoobair"
googleplus_username: "+ZubairAhmed1024"
github_username: "zubair1024"
#codepen_username: "username"
#dribbble_uername: "username"
#medium_username: "@username"
instagram_username: "zubair1024"
pinterest_username: "zubair1024"
linkedin_username: "zubair1024"
#weibo_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
